In [6]:
import os
os.chdir("/Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync")

In [35]:
# Demo code to extract data in python
import h5py

use_channel = 0
with h5py.File('3_0_30.h5', 'r') as f:
    # Data and label are numpy arrays
    data = f['ch{}'.format(use_channel)][()]
    label = f['label'][()]

In [19]:
data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [20]:
label

array([[3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]], dtype=int32)

In [58]:
import os, re
import numpy as np
import h5py
import argparse
import pickle

def get_h5(file_dir):
    return [os.path.join(file_dir, f)
        for f in os.listdir(file_dir)
        if os.path.isfile(os.path.join(file_dir, f)) and 'h5' in f]



def load_data(data_path, mode = 'single_user', nb_frames = 1000000, channels = 4):
    
    data_o = []
    labels_o = []
    return_list = []
    
    num_channel = channels
    if mode == 'cross_user':
        sessions = [2,3,5,6,8,9,10,11,12,13]
    elif mode == 'single_user':
        sessions = [0]


    #numpy init
    if mode == 'cross_user':
        #nb_gestures*nb_sessions*nb_instances*(nb_channels*nb_frames*32*32)
        data = np.zeros((11,10,25,num_channel,nb_frames,32,32))
        # One label per frame
        labels = np.zeros((11,10,25,nb_frames))


    #get gestures files
    source_files = get_h5(data_path)

    for s in source_files:

        d = os.path.basename(s).split('_')
        gestureID, sessionID, inst = int(d[0]), int(d[1]), int(d[2].split('.')[0])

        if sessionID in set(sessions):
            print('Generating', s)
            with h5py.File(s, 'r') as f:
                lab = f['label'][()]
                num_frames = lab.shape[0]
                for c in range(num_channel):
                    # Data and label are numpy arrays
                    data = f['ch{}'.format(c)][()].reshape(num_frames,32,32)
                    data_o.append(data)
                    labels_o.append(lab)
    return_list = [data_o,labels_o]
    return(return_list)
                    
                    #Subsampling
#                    if num_frames > nb_frames:
#                        data_o[gestureID, sessions.index(sessionID), inst, c, :,:,:] = data[:nb_frames]
#                        labels_o[gestureID, sessions.index(sessionID), inst, :] = lab[:nb_frames].squeeze()
#                    else:
#                        data_o[gestureID, sessions.index(sessionID), inst, c, :num_frames,:,:] = data
#                        labels_o[gestureID, sessions.index(sessionID), inst, :num_frames] = lab.squeeze()

In [59]:
Dataset_0 = load_data("/Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync")

Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/1_0_1.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/1_0_31.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/6_0_7.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_6.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/0_0_30.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_6.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_13.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_26.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_42.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/7_0_28.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_34.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1

Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_12.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_27.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/7_0_29.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_43.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_35.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_42.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/6_0_28.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_26.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_13.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_34.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/3_0_1.h5
Generating /Users/fadilboodoo/Desktop/Turing

Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/3_0_31.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/6_0_8.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_9.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/2_0_30.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/0_0_6.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/3_0_15.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/2_0_20.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/3_0_44.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_1.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/7_0_0.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/2_0_45.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/

Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/3_0_43.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_18.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/2_0_0.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_49.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/10_0_43.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/6_0_31.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/10_0_12.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_48.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_19.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/10_0_26.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_6.h5
Generating /Users/fadilboodoo/Desktop/Turi

Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_8.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/10_0_28.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_22.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_17.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_46.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_31.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_47.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_16.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_23.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/0_0_12.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/1_0_27.h5
Generating /Users/fadilboodoo/Desktop/Turin

Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/8_0_32.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/3_0_7.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_44.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_20.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_15.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/9_0_33.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/10_0_39.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_1.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_14.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/4_0_21.h5
Generating /Users/fadilboodoo/Desktop/Turing/M1/Cours/TER/Dataset/dsp.nosync/5_0_45.h5
Generating /Users/fadilboodoo/Desktop/Turing

In [302]:
len(hey)

2

In [299]:
hey[0]

[array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],

In [307]:
len(hey[1])

2200

In [309]:
hey[1][0].shape

(92, 1)

In [318]:
hey[1][2199][82][0]

1

In [298]:
len(hey)

2

In [301]:
hey[0]

[array([[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        ...,
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],


In [293]:
hey[0].shape

(92, 32, 32)

In [281]:
hey[1].shape

(92, 32, 32)

In [282]:
hey[2].shape

(92, 32, 32)

In [283]:
hey[3].shape

(92, 32, 32)

In [290]:
hey[1000].shape

(67, 32, 32)

In [289]:
hey[2198].shape

(83, 32, 32)

In [288]:
hey[2199].shape

(83, 32, 32)

In [50]:
Dataset_0[1][0]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [339]:
Dataset_0[0][0].shape[0]

92

In [28]:
Dataset_0[0][0].shape

(92, 32, 32)

In [334]:
Dataset_0[0][0][0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
NT = Dataset_0[0][0].shape[0]
matrice_conc = Dataset_0[0][0][0]
label_conc = 

for i in range(1, NT):
    matrice_conc = np.concatenate((matrice_conc, Dataset_0[0][0][1]), axis=0, out=None)

In [51]:
matrice_conc.shape

(2944, 32)

In [57]:
Dataset_0[1][0].shape

(92, 1)

In [52]:
import pyriemann
matrice_conv = pyriemann.estimation.Covariances(matrice_conc,Dataset_0[1][0])

TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

In [21]:
matrice_conv

Covariances(estimator=array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

In [49]:
cov = pyriemann.estimation.Covariances().fit_transform(matrice_conc)

ValueError: not enough values to unpack (expected 3, got 2)

In [34]:
cov.shape

(92, 32, 32)

In [35]:
cov = pyriemann.estimation.Covariances().transform(Dataset_0[0][0])

In [36]:
cov.shape

(92, 32, 32)

In [40]:
cov[0][31]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
pyriemann.utils.mean.mean_covariance(cov, metric='riemann', sample_weight=None,)

ValueError: Covariance matrices must be positive definite. Add regularization to avoid this error.